### ISSUE TITLE
th trainMNIST.lua error: SpatialSoftMax.lua:38: bad argument #1 to 'resizeAs' (torch.DoubleTensor expected, got torch.CudaTensor)

### ISSUE THREAD

**Issue by ZhipengLiu6** [dritchie/pixelCNN#1]
Hi Ritchie,

Thank you for the code. 
There is a error, SpatialSoftMax.lua:38: bad argument #1 to 'resizeAs' (torch.DoubleTensor expected, got torch.CudaTensor), when I run the command, th trainMNIST.lua, After I  convert the data type,  torch.CudaTensor, to  torch.DoubleTensor. There is a new error, assertion failed!.  How to deal with it? Thank you for you answering.

**Comment by dritchie** [comment]
Thanks for pointing this out! I must have introduced this bug when I copied this code over from the project it originally came from.
