### ISSUE TITLE
quantize error?

### ISSUE THREAD

**Issue by insperatum** [dritchie/pixelCNN#2]
https://github.com/dritchie/pixelCNN/blob/master/util.lua#L15

If imgData is exactly 1, the pixel quantizes to `quantLevels+1`

**Comment by dritchie** [comment]
`quantize` is designed to work with images that have been passed through `normalizeByteImage`. That function divides each channel by 256 (see [here](https://github.com/dritchie/pixelCNN/blob/master/util.lua#L11)), so its output can never be exactly 1 (the maximum value of a byte-valued pixel is 255).
